# Generated by Django 3.2.7 on 2021-09-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0044_auto_20210920_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventss',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='newss',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='newss',
            name='campname',
        ),
        migrations.AddField(
            model_name='eventss',
            name='years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zgoruban.year_categoryss'),
        ),
        migrations.AddField(
            model_name='newss',
            name='years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zgoruban.year_categoryss'),
        ),
    ]
