# Generated by Django 3.2.7 on 2021-09-20 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0045_auto_20210920_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventss',
            name='years',
        ),
        migrations.RemoveField(
            model_name='newss',
            name='years',
        ),
        migrations.AddField(
            model_name='eventss',
            name='Year',
            field=models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2021', max_length=30),
        ),
        migrations.AddField(
            model_name='newss',
            name='Year',
            field=models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2021', max_length=30),
        ),
        migrations.AddField(
            model_name='newss',
            name='campname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zgoruban.camps'),
        ),
    ]
