# Generated by Django 3.2.7 on 2021-09-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0047_gallerys_heading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GALLERYS',
            new_name='GALLERYSS',
        ),
    ]
