# Generated by Django 3.2.7 on 2021-09-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0048_rename_gallerys_galleryss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryss',
            name='Heading',
        ),
    ]
