# Generated by Django 3.2.7 on 2021-09-20 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zgoruban', '0049_remove_galleryss_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVENTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('years', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zgoruban.year_categoryss')),
            ],
        ),
        migrations.DeleteModel(
            name='EVENTSS',
        ),
        migrations.RemoveField(
            model_name='newss',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='newss',
            name='campname',
        ),
        migrations.AddField(
            model_name='newss',
            name='years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zgoruban.year_categoryss'),
        ),
        migrations.DeleteModel(
            name='GALLERY',
        ),
    ]
